#/bin/sh
cat <<EOT >> /home/vagrant/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcNMYZdfBqV9egLCG6ByTfQI2UcSXauFxswdxqulwIBfkxTbfSTGj68uyhGlg2BD0TpJxkAhOyRwMN+KpjwfJBfuPEHd9zpiGggN4ys151A7Ihzx3YKKU4DesrPJ8ZyAPXaejrgdq5oOkTW7pT0fuwYEJoDRyrgwHRU5/hT9WtlKrWOzp5ASjVZEjWkTQwRSzneQ7FJixQoxwnStqmmV4OlIixd1HonbQ2R+q8yfI74+MBsD+RuzoI7lph2tOyIPzGIlaZjsYtJVxbkUorSUKxBG7Shn4L3VIwdhBCXGv5+Nb0k/m43NHRFZCSo+XOGmTw8AifX0CRdSf8z9fFHpnX vagrant@control-node
EOT